<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<div class="container" style="display: none;">
 <div class="row">
                        <div class="col-md-12 text-center">
                            <div class="conff">
                            <h5 class="payconfirm"></h5>
                            <div class="imgd"></div>
<!--                            <a href="#" data-toggle="modal" data-target="#yellowpay" class="theme-btn btn td-buy-package"> </a>-->
<form name="redirect" action="{{ route('payment.success') }}" method="POST">
                                  @csrf
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="{{ $key }}" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="10" // Amount is in currency subunits. Default currency is INR. Hence, 29935 refers to 29935 paise or INR 299.35.
    data-currency="INR" //You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{ $order->id }}"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay Now "
    data-name="Koxton Sports"
    data-description="Koxton Sports"
    data-image=""
    data-prefill.name="{{ $request->first_name.' '.$request->last_name }}"
    data-prefill.email="{{ $request->email }}"
    data-theme.color="#528FF0"
></script>
<input type="hidden" name="name" value="Koxton Sports">
  <input type="hidden" name="description" value="Koxton Sports">
  <input type="hidden" name="image" value="{{ asset('public/assets/images/lgoo.png' ) }}">
  <input type="hidden" name="first_name" value="{{ $request->first_name.' '.$request->last_name }}">
  <input type="hidden" name="mobile" value="{{ $request->mobile }}">
  <input type="hidden" name="email" value="{{ $request->email }}">
  <input type="hidden" name="notes[shipping address]" value="{{ implode(', ', $request->address) . ', ' . $request->city . ' ' . $state . ' ' . $country.' - '.$request->pincode }}">
  <input type="hidden" name="callback_url" value="{{ route('payment.success') }}">
  <input type="hidden" name="cancel_url" value="{{ route('payment.cancel') }}">
  <input type="hidden" name="cookie" value="{{ $cooked }}">
  <input type="hidden" name="payment_method" value="razorpay">
  <input type="hidden" name="c_coupon" value="{{$request->c_coupon}}">
  <input type="hidden" name="address"value="{{ implode(', ', $request->address) . ', ' . $request->city . ' ' . $state . ' ' . $country.' - '.$request->pincode }}">


</form>
                        </div>
                    </div></div>

</div>
</div>
<div class="modal fade" id="yellowpay" tabindex="-1" role="dialog" aria-labelledby="yellowpayTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="yellowpayTitle"></h5>
        <button type="button" class="close" data-dismiss="modal" style="display: none;" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="">


      </div>
      <div class="modal-footer">

        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>
{{-- <script language='javascript'>document.redirect.submit();</script> --}}


<script type="text/javascript">
    $(document).ready(function(e){
        $('#yellowpay').modal('show');
        $('.razorpay-payment-button').click();
        // setTimeout(function(){ 
        //   document.redirect.submit();
        // }, 2000);
    });

</script>